name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install required system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt-get update

          # Install dependencies with correct names for Ubuntu 24.04
          sudo apt-get install -y libasound2t64 libffi8 libx264-dev || true

          # Fallback handling
          if ! dpkg -s libasound2t64 >/dev/null 2>&1; then
            echo "libasound2t64 not available, installing alsa-utils instead..."
            sudo apt-get install -y alsa-utils
          fi

          if ! dpkg -s libffi8 >/dev/null 2>&1; then
            echo "libffi8 not available, trying libffi-dev..."
            sudo apt-get install -y libffi-dev || echo "libffi-dev also unavailable"
          fi

          if ! dpkg -s libx264-dev >/dev/null 2>&1; then
            echo "libx264-dev not available, skipping..."
          fi
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install-deps || echo "Playwright deps failed, continuing..." && npx playwright install
      - name: Run Cucumber tests
        run: npm test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Report
          path: test-results
          retention-days: 2
